""" Domain pattern to application mapping (ordered by priority)
Keywords are checked against DNS queries and SNI fields"""

DOMAIN_PATTERNS = {
 # ============ SOCIAL MEDIA (50+ patterns) ============
 'facebook': {'app': 'Facebook', 'category': 'Social Media'},
 'fbcdn': {'app': 'Facebook', 'category': 'Social Media'},
 'fbstatic': {'app': 'Facebook', 'category': 'Social Media'},
 'instagram': {'app': 'Instagram', 'category': 'Social Media'},
 'cdninstagram': {'app': 'Instagram', 'category': 'Social Media'},
 'instaproxy': {'app': 'Instagram', 'category': 'Social Media'},
 'whatsapp': {'app': 'WhatsApp', 'category': 'Messaging'},
 'whatsapp-cdn': {'app': 'WhatsApp', 'category': 'Messaging'},
 'wa.me': {'app': 'WhatsApp', 'category': 'Messaging'},
 'twitter': {'app': 'Twitter/X', 'category': 'Social Media'},
 'twimg': {'app': 'Twitter/X', 'category': 'Social Media'},
 'twttr': {'app': 'Twitter/X', 'category': 'Social Media'},
 'twitter-cdn': {'app': 'Twitter/X', 'category': 'Social Media'},
 'x.com': {'app': 'Twitter/X', 'category': 'Social Media'},
 'linkedin': {'app': 'LinkedIn', 'category': 'Professional'},
 'licdn': {'app': 'LinkedIn', 'category': 'Professional'},
 'reddit': {'app': 'Reddit', 'category': 'Social Media'},
 'redd.it': {'app': 'Reddit', 'category': 'Social Media'},
 'redditstatic': {'app': 'Reddit', 'category': 'Social Media'},
 'snapchat': {'app': 'Snapchat', 'category': 'Social Media'},
 'snapchatcdn': {'app': 'Snapchat', 'category': 'Social Media'},
 'tiktok': {'app': 'TikTok', 'category': 'Social Media'},
 'musicallyapp': {'app': 'TikTok', 'category': 'Social Media'},
 'tiktok-cdn': {'app': 'TikTok', 'category': 'Social Media'},
 'douyin': {'app': 'Douyin (TikTok CN)', 'category': 'Social Media'},
 'pinterest': {'app': 'Pinterest', 'category': 'Social Media'},
 'pinimg': {'app': 'Pinterest', 'category': 'Social Media'},
 'tumblr': {'app': 'Tumblr', 'category': 'Social Media'},
 'tumblrcdn': {'app': 'Tumblr', 'category': 'Social Media'},
 'nextdoor': {'app': 'Nextdoor', 'category': 'Social Media'},
 'quora': {'app': 'Quora', 'category': 'Social Media'},
 'medium': {'app': 'Medium', 'category': 'Social Media'},
 'steemit': {'app': 'Steemit', 'category': 'Social Media'},
 'mastodon': {'app': 'Mastodon', 'category': 'Social Media'},
 'bluesky': {'app': 'Bluesky', 'category': 'Social Media'},
 'threads': {'app': 'Threads', 'category': 'Social Media'},
 'bereal': {'app': 'BeReal', 'category': 'Social Media'},
 'vsco': {'app': 'VSCO', 'category': 'Social Media'},
 'weibo': {'app': 'Weibo', 'category': 'Social Media'},
 'xiaohongshu': {'app': 'Little Red Book', 'category': 'Social Media'},
 'kuaishou': {'app': 'Kuaishou', 'category': 'Social Media'},
 'qq.com': {'app': 'QQ', 'category': 'Social Media'},
 'renren': {'app': 'Renren', 'category': 'Social Media'},
 'momo': {'app': 'Momo', 'category': 'Social Media'},

 # ============ VIDEO STREAMING (60+ patterns) ============
 'youtube': {'app': 'YouTube', 'category': 'Video'},
 'googlevideo': {'app': 'YouTube', 'category': 'Video'},
 'ytimg': {'app': 'YouTube', 'category': 'Video'},
 'youtube-cdn': {'app': 'YouTube', 'category': 'Video'},
 'youtu.be': {'app': 'YouTube', 'category': 'Video'},
 'netflix': {'app': 'Netflix', 'category': 'Video'},
 'nflxvideo': {'app': 'Netflix', 'category': 'Video'},
 'netflixcdn': {'app': 'Netflix', 'category': 'Video'},
 'nflximg': {'app': 'Netflix', 'category': 'Video'},
 'primevideo': {'app': 'Amazon Prime', 'category': 'Video'},
 'amazonvideo': {'app': 'Amazon Prime', 'category': 'Video'},
 'atv-ps': {'app': 'Amazon Prime', 'category': 'Video'},
 'hotstar': {'app': 'Disney+ Hotstar', 'category': 'Video'},
 'hotstarcdn': {'app': 'Disney+ Hotstar', 'category': 'Video'},
 'disneyplus': {'app': 'Disney+', 'category': 'Video'},
 'disneycdn': {'app': 'Disney+', 'category': 'Video'},
 'twitch': {'app': 'Twitch', 'category': 'Video'},
 'twitchcdn': {'app': 'Twitch', 'category': 'Video'},
 'hulu': {'app': 'Hulu', 'category': 'Video'},
 'hulucdn': {'app': 'Hulu', 'category': 'Video'},
 'hbo': {'app': 'HBO Max', 'category': 'Video'},
 'hbomax': {'app': 'HBO Max', 'category': 'Video'},
 'peacocktv': {'app': 'Peacock TV', 'category': 'Video'},
 'paramountplus': {'app': 'Paramount+', 'category': 'Video'},
 'appletv': {'app': 'Apple TV+', 'category': 'Video'},
 'vimeo': {'app': 'Vimeo', 'category': 'Video'},
 'vimeocdn': {'app': 'Vimeo', 'category': 'Video'},
 'dailymotion': {'app': 'Dailymotion', 'category': 'Video'},
 'rumble': {'app': 'Rumble', 'category': 'Video'},
 'odysee': {'app': 'Odysee', 'category': 'Video'},
 'bitchute': {'app': 'BitChute', 'category': 'Video'},
 'brighteon': {'app': 'Brighteon', 'category': 'Video'},
 'vk.com': {'app': 'VKontakte Video', 'category': 'Video'},
 'ok.ru': {'app': 'Odnoklassniki', 'category': 'Video'},
 'rutube': {'app': 'RuTube', 'category': 'Video'},
 'livejournal': {'app': 'LiveJournal', 'category': 'Video'},
 'youku': {'app': 'Youku', 'category': 'Video'},
 'iqiyi': {'app': 'iQIYI', 'category': 'Video'},
 'bilibili': {'app': 'Bilibili', 'category': 'Video'},
 'sohu': {'app': 'Sohu Video', 'category': 'Video'},
 'qq.video': {'app': 'Tencent Video', 'category': 'Video'},
 'mgtv': {'app': 'Mango TV', 'category': 'Video'},
 'le.com': {'app': 'LeEco', 'category': 'Video'},
 'vlive': {'app': 'V Live', 'category': 'Video'},
 'wavve': {'app': 'Wavve', 'category': 'Video'},
 'tving': {'app': 'TVING', 'category': 'Video'},
 'watcha': {'app': 'Watcha', 'category': 'Video'},
 'cinemax': {'app': 'Cinemax', 'category': 'Video'},
 'showtime': {'app': 'Showtime', 'category': 'Video'},

 # ============ COMMUNICATION & MESSAGING (50+ patterns) ============
 'zoom': {'app': 'Zoom', 'category': 'Video Call'},
 'zoomcdn': {'app': 'Zoom', 'category': 'Video Call'},
 'teams.microsoft': {'app': 'Microsoft Teams', 'category': 'Video Call'},
 'teams.cdn': {'app': 'Microsoft Teams', 'category': 'Video Call'},
 'meet.google': {'app': 'Google Meet', 'category': 'Video Call'},
 'discord': {'app': 'Discord', 'category': 'Messaging'},
 'discordapp': {'app': 'Discord', 'category': 'Messaging'},
 'discordcdn': {'app': 'Discord', 'category': 'Messaging'},
 'telegram': {'app': 'Telegram', 'category': 'Messaging'},
 't.me': {'app': 'Telegram', 'category': 'Messaging'},
 'slack': {'app': 'Slack', 'category': 'Messaging'},
 'slackb': {'app': 'Slack', 'category': 'Messaging'},
 'skype': {'app': 'Skype', 'category': 'Video Call'},
 'skypeassets': {'app': 'Skype', 'category': 'Video Call'},
 'webex': {'app': 'Webex', 'category': 'Video Call'},
 'webexcdn': {'app': 'Webex', 'category': 'Video Call'},
 'jitsi': {'app': 'Jitsi Meet', 'category': 'Video Call'},
 'whereby': {'app': 'Whereby', 'category': 'Video Call'},
 'whereby.com': {'app': 'Whereby', 'category': 'Video Call'},
 'signal': {'app': 'Signal', 'category': 'Messaging'},
 'signalcdn': {'app': 'Signal', 'category': 'Messaging'},
 'viber': {'app': 'Viber', 'category': 'Messaging'},
 'vibercdn': {'app': 'Viber', 'category': 'Messaging'},
 'line': {'app': 'LINE', 'category': 'Messaging'},
 'wechat': {'app': 'WeChat', 'category': 'Messaging'},
 'weixin': {'app': 'WeChat', 'category': 'Messaging'},
 'qqim': {'app': 'QQ', 'category': 'Messaging'},
 'wire': {'app': 'Wire', 'category': 'Messaging'},
 'threema': {'app': 'Threema', 'category': 'Messaging'},
 'session': {'app': 'Session', 'category': 'Messaging'},
 'briar': {'app': 'Briar', 'category': 'Messaging'},
 'matrix': {'app': 'Matrix', 'category': 'Messaging'},
 'element': {'app': 'Element', 'category': 'Messaging'},
 'rocket.chat': {'app': 'Rocket.Chat', 'category': 'Messaging'},
 'mattermost': {'app': 'Mattermost', 'category': 'Messaging'},
 'keybase': {'app': 'Keybase', 'category': 'Messaging'},

 # ============ GAMING (80+ patterns) ============
 'steampowered': {'app': 'Steam', 'category': 'Gaming'},
 'steamcdn': {'app': 'Steam', 'category': 'Gaming'},
 'steamstatic': {'app': 'Steam', 'category': 'Gaming'},
 'epicgames': {'app': 'Epic Games', 'category': 'Gaming'},
 'epiccdn': {'app': 'Epic Games', 'category': 'Gaming'},
 'riotgames': {'app': 'Riot Games', 'category': 'Gaming'},
 'lol': {'app': 'League of Legends', 'category': 'Gaming'},
 'valorant': {'app': 'Valorant', 'category': 'Gaming'},
 'ea.com': {'app': 'EA Games', 'category': 'Gaming'},
 'eacdn': {'app': 'EA Games', 'category': 'Gaming'},
 'origin': {'app': 'Origin', 'category': 'Gaming'},
 'playstation': {'app': 'PlayStation', 'category': 'Gaming'},
 'psn': {'app': 'PlayStation Network', 'category': 'Gaming'},
 'xbox': {'app': 'Xbox', 'category': 'Gaming'},
 'xboxlive': {'app': 'Xbox Live', 'category': 'Gaming'},
 'blizzard': {'app': 'Blizzard', 'category': 'Gaming'},
 'battle.net': {'app': 'Battle.net', 'category': 'Gaming'},
 'worldofwarcraft': {'app': 'World of Warcraft', 'category': 'Gaming'},
 'diablo': {'app': 'Diablo', 'category': 'Gaming'},
 'overwatch': {'app': 'Overwatch', 'category': 'Gaming'},
 'hearthstone': {'app': 'Hearthstone', 'category': 'Gaming'},
 'ubi': {'app': 'Ubisoft', 'category': 'Gaming'},
 'ubisoft': {'app': 'Ubisoft', 'category': 'Gaming'},
 'ubisoftcdn': {'app': 'Ubisoft', 'category': 'Gaming'},
 'activision': {'app': 'Activision', 'category': 'Gaming'},
 'bethesda': {'app': 'Bethesda', 'category': 'Gaming'},
 'elderscrolls': {'app': 'Elder Scrolls', 'category': 'Gaming'},
 'fallout': {'app': 'Fallout', 'category': 'Gaming'},
 'mojang': {'app': 'Minecraft', 'category': 'Gaming'},
 'minecraft': {'app': 'Minecraft', 'category': 'Gaming'},
 'roblox': {'app': 'Roblox', 'category': 'Gaming'},
 'robloxcdn': {'app': 'Roblox', 'category': 'Gaming'},
 'fortnite': {'app': 'Fortnite', 'category': 'Gaming'},
 'pubg': {'app': 'PUBG', 'category': 'Gaming'},
 'apex': {'app': 'Apex Legends', 'category': 'Gaming'},
 'csgo': {'app': 'CS:GO', 'category': 'Gaming'},
 'counter-strike': {'app': 'Counter-Strike', 'category': 'Gaming'},
 'dota': {'app': 'Dota 2', 'category': 'Gaming'},
 'gta': {'app': 'GTA Online', 'category': 'Gaming'},
 'rockstargames': {'app': 'Rockstar Games', 'category': 'Gaming'},
 'supercell': {'app': 'Supercell', 'category': 'Gaming'},
 'clash': {'app': 'Clash of Clans', 'category': 'Gaming'},
 'clashroyal': {'app': 'Clash Royale', 'category': 'Gaming'},
 'brawlstars': {'app': 'Brawl Stars', 'category': 'Gaming'},
 'pokemongo': {'app': 'Pokémon GO', 'category': 'Gaming'},
 'niantic': {'app': 'Niantic', 'category': 'Gaming'},
 'zynga': {'app': 'Zynga', 'category': 'Gaming'},
 'kingcdn': {'app': 'King', 'category': 'Gaming'},
 'playrix': {'app': 'Playrix', 'category': 'Gaming'},
 'scopely': {'app': 'Scopely', 'category': 'Gaming'},
 'glu': {'app': 'Glu Mobile', 'category': 'Gaming'},
 'netease': {'app': 'NetEase Games', 'category': 'Gaming'},
 'tencent': {'app': 'Tencent Games', 'category': 'Gaming'},
 'mihoyo': {'app': 'MiHoYo', 'category': 'Gaming'},
 'genshin': {'app': 'Genshin Impact', 'category': 'Gaming'},
 'honkai': {'app': 'Honkai: Star Rail', 'category': 'Gaming'},
 'nexon': {'app': 'Nexon', 'category': 'Gaming'},
 'ncsoft': {'app': 'NCSoft', 'category': 'Gaming'},
 'bandainamco': {'app': 'Bandai Namco', 'category': 'Gaming'},

 # ============ CLOUD & SERVICES (80+ patterns) ============
 'googleapis': {'app': 'Google Services', 'category': 'Cloud'},
 'google': {'app': 'Google', 'category': 'Search'},
 'googlesyndication': {'app': 'Google Ads', 'category': 'Advertising'},
 'gstatic': {'app': 'Google Static', 'category': 'CDN'},
 'googleusercontent': {'app': 'Google', 'category': 'Cloud'},
 'doubleclick': {'app': 'DoubleClick', 'category': 'Advertising'},
 'googleadservices': {'app': 'Google Ads', 'category': 'Advertising'},
 'googleapis.com': {'app': 'Google APIs', 'category': 'Cloud'},
 'amazonaws': {'app': 'AWS', 'category': 'Cloud'},
 'awscdn': {'app': 'AWS CDN', 'category': 'CDN'},
 'cloudfront': {'app': 'CloudFront', 'category': 'CDN'},
 'cloudflare': {'app': 'Cloudflare', 'category': 'CDN'},
 'cdnjs': {'app': 'Cloudflare CDNJS', 'category': 'CDN'},
 'akamai': {'app': 'Akamai CDN', 'category': 'CDN'},
 'microsoft': {'app': 'Microsoft', 'category': 'Cloud'},
 'apple': {'app': 'Apple Services', 'category': 'Cloud'},
 'icloud': {'app': 'iCloud', 'category': 'Cloud'},
 'icloudcdn': {'app': 'iCloud', 'category': 'Cloud'},
 'dropbox': {'app': 'Dropbox', 'category': 'Cloud'},
 'dropboxcdn': {'app': 'Dropbox', 'category': 'Cloud'},
 'office.com': {'app': 'Microsoft 365', 'category': 'Cloud'},
 'office365': {'app': 'Microsoft 365', 'category': 'Cloud'},
 'sharepoint': {'app': 'SharePoint', 'category': 'Cloud'},
 'live.com': {'app': 'Microsoft Live', 'category': 'Cloud'},
 'msftauth': {'app': 'Microsoft Auth', 'category': 'Cloud'},
 'gcp': {'app': 'Google Cloud', 'category': 'Cloud'},
 'azurecdn': {'app': 'Microsoft Azure', 'category': 'Cloud'},
 'fastly': {'app': 'Fastly CDN', 'category': 'CDN'},
 'limelight': {'app': 'Limelight CDN', 'category': 'CDN'},
 'edgecast': {'app': 'Edgecast CDN', 'category': 'CDN'},
 'maxcdn': {'app': 'MaxCDN', 'category': 'CDN'},
 'stackpath': {'app': 'StackPath', 'category': 'CDN'},
 'bunnycdn': {'app': 'BunnyCDN', 'category': 'CDN'},
 'digitalocean': {'app': 'DigitalOcean', 'category': 'Cloud'},
 'heroku': {'app': 'Heroku', 'category': 'Cloud'},
 'railway': {'app': 'Railway', 'category': 'Cloud'},
 'render': {'app': 'Render', 'category': 'Cloud'},
 'vercel': {'app': 'Vercel', 'category': 'Cloud'},
 'netlify': {'app': 'Netlify', 'category': 'Cloud'},
 'github': {'app': 'GitHub', 'category': 'Development'},
 'githubassets': {'app': 'GitHub', 'category': 'Development'},
 'githubusercontent': {'app': 'GitHub', 'category': 'Development'},
 'gitlab': {'app': 'GitLab', 'category': 'Development'},
 'gitlabcdn': {'app': 'GitLab', 'category': 'Development'},
 'bitbucket': {'app': 'Bitbucket', 'category': 'Development'},
 'gitea': {'app': 'Gitea', 'category': 'Development'},

 # ============ MUSIC & AUDIO (40+ patterns) ============
 'spotify': {'app': 'Spotify', 'category': 'Music'},
 'scdn': {'app': 'Spotify', 'category': 'Music'},
 'spotifycdn': {'app': 'Spotify', 'category': 'Music'},
 'pandora': {'app': 'Pandora', 'category': 'Music'},
 'apple-music': {'app': 'Apple Music', 'category': 'Music'},
 'applemusic': {'app': 'Apple Music', 'category': 'Music'},
 'music.apple': {'app': 'Apple Music', 'category': 'Music'},
 'amazonmusic': {'app': 'Amazon Music', 'category': 'Music'},
 'tidal': {'app': 'Tidal', 'category': 'Music'},
 'tidalmusic': {'app': 'Tidal', 'category': 'Music'},
 'soundcloud': {'app': 'SoundCloud', 'category': 'Music'},
 'sndcdn': {'app': 'SoundCloud', 'category': 'Music'},
 'bandcamp': {'app': 'Bandcamp', 'category': 'Music'},
 'deezer': {'app': 'Deezer', 'category': 'Music'},
 'qobuz': {'app': 'Qobuz', 'category': 'Music'},
 'audible': {'app': 'Audible', 'category': 'Music'},
 'audiobooks': {'app': 'Audiobooks', 'category': 'Music'},
 'podcast': {'app': 'Podcasts', 'category': 'Music'},
 'podbean': {'app': 'Podbean', 'category': 'Music'},
 'transistor': {'app': 'Transistor', 'category': 'Music'},
 'anchor': {'app': 'Anchor', 'category': 'Music'},
 'buzzsprout': {'app': 'Buzzsprout', 'category': 'Music'},

 # ============ SHOPPING & PAYMENT (60+ patterns) ============
 'amazon': {'app': 'Amazon', 'category': 'Shopping'},
 'amazoncdn': {'app': 'Amazon', 'category': 'Shopping'},
 'ebay': {'app': 'eBay', 'category': 'Shopping'},
 'walmart': {'app': 'Walmart', 'category': 'Shopping'},
 'walmarttcdn': {'app': 'Walmart', 'category': 'Shopping'},
 'shopify': {'app': 'Shopify', 'category': 'Shopping'},
 'shopifycdn': {'app': 'Shopify', 'category': 'Shopping'},
 'etsy': {'app': 'Etsy', 'category': 'Shopping'},
 'target': {'app': 'Target', 'category': 'Shopping'},
 'costco': {'app': 'Costco', 'category': 'Shopping'},
 'homedepot': {'app': 'Home Depot', 'category': 'Shopping'},
 'lowes': {'app': 'Lowes', 'category': 'Shopping'},
 'bestbuy': {'app': 'Best Buy', 'category': 'Shopping'},
 'ikea': {'app': 'IKEA', 'category': 'Shopping'},
 'h-and-m': {'app': 'H&M', 'category': 'Shopping'},
 'zara': {'app': 'Zara', 'category': 'Shopping'},
 'uniqlo': {'app': 'Uniqlo', 'category': 'Shopping'},
 'forever21': {'app': 'Forever 21', 'category': 'Shopping'},
 'gap': {'app': 'Gap', 'category': 'Shopping'},
 'nike': {'app': 'Nike', 'category': 'Shopping'},
 'adidas': {'app': 'Adidas', 'category': 'Shopping'},
 'puma': {'app': 'Puma', 'category': 'Shopping'},
 'footlocker': {'app': 'Foot Locker', 'category': 'Shopping'},
 'aliexpress': {'app': 'AliExpress', 'category': 'Shopping'},
 'alicdn': {'app': 'AliExpress', 'category': 'Shopping'},
 'wish': {'app': 'Wish', 'category': 'Shopping'},
 'gearbest': {'app': 'Gearbest', 'category': 'Shopping'},
 'banggood': {'app': 'Banggood', 'category': 'Shopping'},
 'dhgate': {'app': 'DHgate', 'category': 'Shopping'},
 'taobao': {'app': 'Taobao', 'category': 'Shopping'},
 'tmall': {'app': 'Tmall', 'category': 'Shopping'},
 'jd.com': {'app': 'JD.com', 'category': 'Shopping'},
 'suning': {'app': 'Suning', 'category': 'Shopping'},
 'flipkart': {'app': 'Flipkart', 'category': 'Shopping'},
 'snapdeal': {'app': 'Snapdeal', 'category': 'Shopping'},
 'paytm': {'app': 'Paytm', 'category': 'Shopping'},
 'myntra': {'app': 'Myntra', 'category': 'Shopping'},
 'olx': {'app': 'OLX', 'category': 'Shopping'},
 'quikr': {'app': 'Quikr', 'category': 'Shopping'},
 'paypal': {'app': 'PayPal', 'category': 'Payment'},
 'paypalsecurity': {'app': 'PayPal', 'category': 'Payment'},
 'stripe': {'app': 'Stripe', 'category': 'Payment'},
 'square': {'app': 'Square', 'category': 'Payment'},
 'skrill': {'app': 'Skrill', 'category': 'Payment'},
 'neteller': {'app': 'Neteller', 'category': 'Payment'},
 '2checkout': {'app': '2Checkout', 'category': 'Payment'},

 # ============ SOCIAL & PROFESSIONAL (50+ patterns) ============
 'indeed': {'app': 'Indeed', 'category': 'Job Search'},
 'glassdoor': {'app': 'Glassdoor', 'category': 'Job Search'},
 'monster': {'app': 'Monster', 'category': 'Job Search'},
 'linkedin-events': {'app': 'LinkedIn Events', 'category': 'Professional'},
 'hackerrank': {'app': 'HackerRank', 'category': 'Learning'},
 'leetcode': {'app': 'LeetCode', 'category': 'Learning'},
 'codechef': {'app': 'CodeChef', 'category': 'Learning'},
 'codeforces': {'app': 'Codeforces', 'category': 'Learning'},
 'projecteuler': {'app': 'Project Euler', 'category': 'Learning'},

 # ============ NEWS & MEDIA (50+ patterns) ============
 'bbc': {'app': 'BBC', 'category': 'News'},
 'cnn': {'app': 'CNN', 'category': 'News'},
 'nytimes': {'app': 'New York Times', 'category': 'News'},
 'theguardian': {'app': 'The Guardian', 'category': 'News'},
 'reuters': {'app': 'Reuters', 'category': 'News'},
 'apnews': {'app': 'AP News', 'category': 'News'},
 'huffpost': {'app': 'HuffPost', 'category': 'News'},
 'buzzfeed': {'app': 'BuzzFeed', 'category': 'News'},
 'dailymail': {'app': 'Daily Mail', 'category': 'News'},
 'foxnews': {'app': 'Fox News', 'category': 'News'},
 'bbc.com': {'app': 'BBC', 'category': 'News'},

 # ============ PRODUCTIVITY & OFFICE (40+ patterns) ============
 'notion': {'app': 'Notion', 'category': 'Productivity'},
 'notioncdn': {'app': 'Notion', 'category': 'Productivity'},
 'evernote': {'app': 'Evernote', 'category': 'Productivity'},
 'onenote': {'app': 'OneNote', 'category': 'Productivity'},
 'todoist': {'app': 'Todoist', 'category': 'Productivity'},
 'asana': {'app': 'Asana', 'category': 'Productivity'},
 'monday': {'app': 'Monday.com', 'category': 'Productivity'},
 'trello': {'app': 'Trello', 'category': 'Productivity'},
 'jira': {'app': 'Jira', 'category': 'Productivity'},
 'confluence': {'app': 'Confluence', 'category': 'Productivity'},
 'notion.so': {'app': 'Notion', 'category': 'Productivity'},
 'drive.google': {'app': 'Google Drive', 'category': 'Cloud Storage'},
 'docs.google': {'app': 'Google Docs', 'category': 'Productivity'},
 'sheets.google': {'app': 'Google Sheets', 'category': 'Productivity'},

 # ============ VPN & PRIVACY (30+ patterns) ============
 'expressvpn': {'app': 'ExpressVPN', 'category': 'VPN'},
 'nordvpn': {'app': 'NordVPN', 'category': 'VPN'},
 'surfshark': {'app': 'Surfshark', 'category': 'VPN'},
 'cyberghost': {'app': 'CyberGhost', 'category': 'VPN'},
 'protonvpn': {'app': 'ProtonVPN', 'category': 'VPN'},
 'mullvad': {'app': 'Mullvad VPN', 'category': 'VPN'},
 'windscribe': {'app': 'Windscribe', 'category': 'VPN'},
 'hotspot': {'app': 'Hotspot Shield', 'category': 'VPN'},
 'privatevpn': {'app': 'Private VPN', 'category': 'VPN'},
 'ipvanish': {'app': 'IPVanish', 'category': 'VPN'},
 'torproject': {'app': 'Tor Browser', 'category': 'Privacy'},
 'tails': {'app': 'Tails OS', 'category': 'Privacy'},

 # ============ BANKING & FINANCE (50+ patterns) ============
 'revolut': {'app': 'Revolut', 'category': 'Finance'},
 'wise': {'app': 'Wise', 'category': 'Finance'},
 'transferwise': {'app': 'Wise', 'category': 'Finance'},
 'n26': {'app': 'N26', 'category': 'Finance'},
 'monzo': {'app': 'Monzo', 'category': 'Finance'},
 'hdfc': {'app': 'HDFC Bank', 'category': 'Finance'},
 'icici': {'app': 'ICICI Bank', 'category': 'Finance'},
 'axis': {'app': 'Axis Bank', 'category': 'Finance'},
 'sbi': {'app': 'SBI', 'category': 'Finance'},
 'yodlee': {'app': 'Yodlee', 'category': 'Finance'},
 'zerodha': {'app': 'Zerodha', 'category': 'Finance'},
 'upstox': {'app': 'Upstox', 'category': 'Finance'},
 'groww': {'app': 'Groww', 'category': 'Finance'},
}
